export default {
  "login": "Omar23Seleem",
  "id": 57719370,
  "node_id": "MDQ6VXNlcjU3NzE5Mzcw",
  "avatar_url": "https://avatars.githubusercontent.com/u/57719370?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Omar23Seleem",
  "html_url": "https://github.com/Omar23Seleem",
  "followers_url": "https://api.github.com/users/Omar23Seleem/followers",
  "following_url": "https://api.github.com/users/Omar23Seleem/following{/other_user}",
  "gists_url": "https://api.github.com/users/Omar23Seleem/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Omar23Seleem/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Omar23Seleem/subscriptions",
  "organizations_url": "https://api.github.com/users/Omar23Seleem/orgs",
  "repos_url": "https://api.github.com/users/Omar23Seleem/repos",
  "events_url": "https://api.github.com/users/Omar23Seleem/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Omar23Seleem/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Omar Seleem",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 8,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2019-11-13T15:09:50Z",
  "updated_at": "2021-08-22T06:45:38Z"
}
